set(CPACK_PACKAGE_DESCRIPTION "A game engine that roars!")
set(CPACK_PACKAGE_VENDOR "G-Epitech")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "R-Type")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "R-Type game")
set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_CONTACT "yann.masson@epitech.eu" "dragos.suceveanu@epitech.eu")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")

set(CPACK_STRIP_FILES "TRUE")

set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_INSTALL_DIRECTORY "R-Type")
set(CPACK_NSIS_CREATE_ICONS_GROUP "R-Type")
set(CPACK_NSIS_MUI_WELCOMEPAGE_TITLE "R-Type")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin/r-type_client.exe")
set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/assets/icons/R-Type.ico")

include(CPack)
