CREATE DATABASE IF NOT EXISTS rtype;

USE rtype;

CREATE TABLE IF NOT EXISTS `scores`
(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `room_name` VARCHAR(30) NOT NULL,
    `score` INT NOT NULL DEFAULT 0,
    `win` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` DATETIME DEFAULT NOW()
);
