set(CPACK_GENERATOR "TGZ;DEB")

set(CLIENT_BINARY r-type_client)
set(CLIENT_LIBS abra r-type_ECS_sdk)

install(TARGETS ${CLIENT_BINARY}
        CONFIGURATIONS Release
        RUNTIME_DEPENDENCIES
        DESTINATION bin)

install(TARGETS ${CLIENT_LIBS}
        CONFIGURATIONS Release
        RUNTIME_DEPENDENCIES
        DESTINATION bin)
