if (WIN32)
    set(PLATFORM_FLAGS "-GNinja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe")
elseif (UNIX)
    set(PLATFORM_FLAGS "-GUnix Makefiles")
    set(CMAKE_MAKE_PROGRAM "make")
    set(CMAKE_C_COMPILER "gcc")
    set(CMAKE_CXX_COMPILER "g++")
endif ()
